### ISSUE TITLE
conflict when colocating job using bpm with concourse worker garden runc

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/bpm-release#67] opened 2018-07-02 15:17 UTC
Since bosh switch to bpm by default (without option to disable it), concourse worker, which we colocate with bosh in [BUCC](https://github.com/starkandwayne/bucc), stops working.

When concourse tries to create a garden (runc) container it encounters the following error:
```
runc create: exit status 1: container_linux.go:295: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:57: mounting \\\"cgroup\\\" to rootfs \\\"/var/vcap/data/baggageclaim/volumes/live/7bc52091-48a7-4f14-69c8-a802bfeb3348/volume\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /cgroup/bpm/blkio/garden/97409a1f-dd85-4003-76de-cddb509aceec: permission denied\\\"\""
```

After tries different combinations of garden version's with and without bpm enabled. We found we could work around this issue by unmounting `/cgroup/bpm/*`:
```
for id in $(/var/vcap/packages/runc/bin/runc list | cut -d' ' -f1); do /var/vcap/packages/runc/bin/runc delete "${id}"; done
umount /cgroup/bpm/*
```

This proves to us that these mountpoints affect other processes, which is unexpected.

**Comment by xoebus** [comment] 2018-07-03 01:57
Thanks for opening this issue!

We're going to try a fix for this here: https://www.pivotaltracker.com/story/show/158469967 (it's the next issue in the backlog). There's still some finger pointing between us and Garden as to the root cause but this should be fixed in the next release.

**Comment by xoebus** [comment] 2018-07-24 21:54
The fix for this has just gone in on master. It should be out in the next release.

**Closed by xoebus** 2018-07-24 21:54 UTC
Labels: bug, delivered

**Comment by ramonskie** [comment] 2018-08-08 16:19
when can we expect the next release???

**Comment by xoebus** [comment] 2018-08-08 18:45
Soon™.

Our pipeline is currently unhappy with some underlying infrastructure changes which is blocking the release.

**Comment by xoebus** [comment] 2018-08-14 21:26
Released!
